# meta_04 - BeeGFS HA Metadata Resource Group

# This is a template for BeeGFS HA metadata resource group. Review all comments and update with all expected values.
# IMPORTANT: All capitalized words in angled brackets must be updated.

beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: 8045
  connMetaPortUDP: 8045
  tuneBindToNumaZone: 1

floating_ips:
  - i4b:100.128.102.4/16
  - i3b:100.127.101.4/16

beegfs_service: metadata

beegfs_targets:
  eseries_storage_system_02:
    eseries_storage_pool_configuration:
      - name: beegfs_m3_m4_m7_m8
        raid_level: raid1
        criteria_drive_count: 4
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.25
            owning_controller: B
