# meta_23 - BeeGFS HA Metadata Resource Group
beegfs_ha_beegfs_meta_conf_resource_group_options:
  connMetaPortTCP: 8075
  connMetaPortUDP: 8075
  tuneBindToNumaZone: 1

floating_ips:
  - i3b:192.168.9.123/24
  - i4b:192.168.10.123/24

beegfs_service: metadata

beegfs_targets:
  eseries_storage_system_06:
    eseries_storage_pool_configuration:
      - name: beegfs_m19_m20_m23_m24
        raid_level: raid1
        criteria_drive_count: 4
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.5
            owning_controller: A