# stor_01 - BeeGFS HA Storage Resource Group

# This is a template for BeeGFS HA storage resource group. Review all comments and update with all expected values.
# IMPORTANT: All capitalized words in angled brackets must be updated.

beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8073
  connStoragePortUDP: 8073
  tuneBindToNumaZone: 1

floating_ips:
  - i3b:100.127.103.7/16
  - i4b:100.128.104.7/16

beegfs_service: storage

beegfs_targets:
  eseries_storage_system_02:
    eseries_storage_pool_configuration:
      - name: beegfs_s7_s8
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.50
            owning_controller: A
          - size: 21.50
            owning_controller: A
