# stor_23 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8073
  connStoragePortUDP: 8073
  tuneBindToNumaZone: 1

floating_ips:
  - i3b:100.127.103.23/16
  - i4b:100.128.104.23/16

beegfs_service: storage

beegfs_targets:
  eseries_storage_system_06:
    eseries_storage_pool_configuration:
      - name: beegfs_s23_s24
        raid_level: raid6
        criteria_drive_count: 12
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.5
            owning_controller: A          
          - size: 21.5
            owning_controller: A          
