# stor_17 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8013
  connStoragePortUDP: 8013
  tuneBindToNumaZone: 0

floating_ips:
  - i1b:100.127.103.17/16
  - i2b:100.128.104.17/16

beegfs_service: storage

beegfs_targets:
  eseries_storage_system_05:
    eseries_storage_pool_configuration:
      - name: beegfs_s17_s18
        raid_level: raid6
        criteria_drive_count: 12
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.5
            owning_controller: A          
          - size: 21.5
            owning_controller: A          
