# stor_05 - BeeGFS HA Storage Resource Group

# This is a template for BeeGFS HA storage resource group. Review all comments and update with all expected values.
# IMPORTANT: All capitalized words in angled brackets must be updated.

beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8053
  connStoragePortUDP: 8053
  tuneBindToNumaZone: 0

floating_ips:
  - i1b:100.127.103.5/16
  - i2b:100.128.104.5/16

beegfs_service: storage

beegfs_targets:
  eseries_storage_system_01:
    eseries_storage_pool_configuration:
      - name: beegfs_s5_s6
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 128
        volumes:
          - size: 21.50
            owning_controller: A
          - size: 21.50
            owning_controller: A
