- name: Add volume paths to storage/metadata_volumes.
  set_fact:
    storage_volumes: |-
      {%- set volumes = [] %}
      {%- for volume in storage_volumes -%}
        {%- if volume.update({"path": storage_volume_paths[volume["name"]]["path"],
                              "host_wwid": storage_volume_paths[volume["name"]]["host_wwid"]}) -%}{%- endif -%}
        {%- if volumes.append(volume) -%}{%- endif -%}
      {%- endfor -%}
      {{ volumes | list }}
    metadata_volumes: |-
      {%- set volumes = [] %}
      {%- for volume in metadata_volumes -%}
        {%- if volume.update({"path": metadata_volume_paths[volume["name"]]["path"],
                              "host_wwid": metadata_volume_paths[volume["name"]]["host_wwid"]}) -%}{%- endif -%}
        {%- if volumes.append(volume) -%}{%- endif -%}
      {%- endfor -%}
      {{ volumes | list }}
