- name: Get the multipathd maps
  command: multipathd show maps raw format "%w,%n"
  register: multipath_maps
  changed_when: false
  become: true

- name: Find mapped metadata volumes.
  set_fact:
    metadata_volume_paths: |-
      {%- set paths = {} -%}
      {%- for volume in metadata_volumes -%}
        {%- if paths.update({volume["name"]: {"path": "", "host_wwid": "", "host_port_protocols": volume["host_port_protocols"]}}) -%}{%- endif -%}
      {%- endfor -%}
      {%- for volume in metadata_volumes -%}
        {%- for map in multipath_maps["stdout_lines"] | default([])-%}
          {%- set map_info = map.split(",") -%}

          {%- if (volume["wwn"] and map_info[0] | regex_search(volume["wwn"], ignorecase=True)) or
                 (volume["eui"] and map_info[0] | regex_search(volume["eui"], ignorecase=True)) -%}
            {%- if paths[volume["name"]].update({"path": "/dev/mapper/" ~ map_info[1], "host_wwid": map_info[0]}) -%}{%- endif -%}
          {%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ paths }}

- name: Find mapped storage volumes.
  set_fact:
    storage_volume_paths: |-
      {%- set paths = {} -%}
      {%- for volume in storage_volumes -%}
        {%- if paths.update({volume["name"]: {"path": "", "host_wwid": "", "host_port_protocols": volume["host_port_protocols"]}}) -%}{%- endif -%}
      {%- endfor -%}
      {%- for volume in storage_volumes -%}
        {%- for map in multipath_maps["stdout_lines"] | default([])-%}
          {%- set map_info = map.split(",") -%}

          {%- if (volume["wwn"] and map_info[0] | regex_search(volume["wwn"], ignorecase=True)) or
                 (volume["eui"] and map_info[0] | regex_search(volume["eui"], ignorecase=True)) -%}
            {%- if paths[volume["name"]].update({"path": "/dev/mapper/" ~ map_info[1], "host_wwid": map_info[0]}) -%}{%- endif -%}
          {%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ paths }}

- name: Determine whether mapped metadata volumes are missing.
  set_fact:
    metadata_rescan: |-
      {%- set rescan = [] -%}
      {%- for key, value in metadata_volume_paths.items() -%}
        {%- if value["path"] == "" -%}
          {%- for protocol in value["host_port_protocols"] if protocol in beegfs_discovery_protocol_list -%}
            {%- if rescan.append(protocol) -%}{%- endif -%}
          {%- endfor -%}
        {%- endif -%}
      {%- endfor -%}
      {{ rescan }}

- name: Determine whether mapped storage volumes are missing.
  set_fact:
    storage_rescan: |-
      {%- set rescan = [] -%}
      {%- for key, value in storage_volume_paths.items() -%}
        {%- if value["path"] == "" -%}
          {%- for protocol in value["host_port_protocols"] if protocol in beegfs_discovery_protocol_list -%}
            {%- if rescan.append(protocol) -%}{%- endif -%}
          {%- endfor -%}
        {%- endif -%}
      {%- endfor -%}
      {{ rescan }}

- name: Determine whether volumes are missing and what actions are required.
  set_fact:
    rescan_actions: |-
      {%- set actions = [] -%}
      {%- for protocol in metadata_rescan + storage_rescan -%}
        {%- if protocol in beegfs_discovery_protocol_list -%}
          {%- if actions.append("rescan") -%}{%- endif -%}
        {%- endif -%}
        {%- if protocol in beegfs_discovery_rescan_iscsi_session_protocol_list -%}
          {%- if actions.append("rescan_iscsi_sessions") -%}{%- endif -%}
        {%- endif -%}
        {%- if protocol in beegfs_discovery_rescan_scsi_bus_protocol_list -%}
          {%- if actions.append("rescan_scsi_bus") -%}{%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {{- actions -}}
