- name: Collect facts about systemd services.
  service_facts:
  become: true

- name: Ensure the required firewall ports are open.
  firewalld:
    state: enabled
    permanent: true
    service: high-availability
  ignore_errors: true
  become: true
  when: beegfs_ha_allow_firewall_high_availability_service == True and 'firewalld.service' in (ansible_facts['services'].keys() | list) and ansible_facts['services']['firewalld.service']['status'] == 'enabled'
