- name: Add /etc/hosts entries for all BeeGFS cluster hosts with the same management node IP address.
  blockinfile:
    path: /etc/hosts
    marker: "# Managed by E-Series Ansible for {{ beegfs_ha_cluster_name }} - {mark}"
    block: |-
      {% for host in ansible_play_hosts_all if host in groups[beegfs_ha_ansible_cluster_group] and "ansible_host" in (hostvars[host].keys() | list) %}
        {{- hostvars[host]["ansible_host"] }}	{{ host }}	{{ hostvars[host]["ansible_hostname"] }}
      {% endfor %}

      {{ beegfs_ha_mgmtd_floating_ip }}	{{ management_info['resource_group'] }}
  become: true

- name: Add required BeeGFS sysctl.conf entries.
  sysctl:
    name: "{{ item['key'] }}"
    value: "{{ item['value'] }}"
    state: present
    reload: true
    sysctl_file: "{{ sysctl_conf_path }}"
  loop: "{{ lookup('dict', beegfs_ha_required_sysctl_entries) }}"
  become: true
