- name: Add /etc/hosts entries for all BeeGFS cluster hosts with the same management node IP address.
  blockinfile:
    path: /etc/hosts
    marker: "# Managed by E-Series Ansible for {{ beegfs_ha_cluster_name }} - {mark}"
    block: |-
      {% for host in ansible_play_hosts_all if host in groups[beegfs_ha_ansible_cluster_group] and "ansible_host" in (hostvars[host].keys() | list) %}
        {{- hostvars[host]["ansible_host"] }} {{ host }} {{ hostvars[host]["ansible_hostname"] }}
      {% endfor %}

      {{ beegfs_ha_mgmtd_floating_ip }} {{ management_info['resource_group'] }}
  register: etc_hosts
  become: true

- name: Configure postfix service for alerts.
  block:
    - name: Configure postfix service
      netapp_eseries.beegfs.update_conf:
        path: "{{ beegfs_ha_alert_conf }}"
        options: "{{ beegfs_ha_alert_conf_default_options | combine(beegfs_ha_alert_conf_ha_group_options) | combine(beegfs_ha_alert_conf_options) | combine(beegfs_ha_alerts_conf_required_options) }}"
        mode: "0644"
      register: postfix_config
      vars:
        beegfs_ha_alerts_conf_required_options:
          myhostname: "{{ alerts_configuration_options['myhostname'] | default(ansible_fqdn | default(ansible_hostname | default(inventory_hostname))) }}"
          mydomain: "{{ alerts_configuration_options['mydomain'] | default(ansible_domain) }}"

    - name: Ensure postfix service is started and enabled.
      ansible.builtin.systemd:
        state: '{% if postfix_config["changed"] %}restarted{% else %}started{% endif %}'
        enabled: true
        name: postfix.service
      become: true
  when: beegfs_ha_enable_alerts
