- name: Ensure the BeeGFS management package is uninstalled (Debian/Ubuntu - Management).
  apt:
    state: absent
    name: beegfs-mgmtd
  when: '"management" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS metadata package is uninstalled (Debian/Ubuntu - Metadata).
  apt:
    state: absent
    name: beegfs-meta
  when: '"metadata" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS storage package is uninstalled (Debian/Ubuntu - Storage).
  apt:
    state: absent
    name: beegfs-storage
  when: '"storage" in beegfs_node_roles'
  become: true

- name: Ensure BeeGFS infiniband package is uninstalled (Debian/Ubuntu - Metadata/Storage).
  apt:
    state: absent
    name: libbeegfs-ib
  when: '("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles) and beegfs_enable_rdma'
  become: true

- name: Ensure BeeGFS client package is uninstalled (Debian/Ubuntu - Client).
  apt:
    state: absent
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
      - libelf-dev
  when: '"client" in beegfs_node_roles'
  become: true

- name: Remove BeeGFS apt respository (Debian/Ubuntu).
  apt_key:
    state: absent
    url: "{{ beegfs_debian_repository_gpgkey }}"
  become: yes

- apt_repository:
    state: absent
    repo: "deb [arch=amd64] {{ beegfs_debian_repository_base_url }} stretch non-free"
    update_cache: yes
  become: yes
