- name: Ensure the BeeGFS management package is uninstalled (RedHat/CentOS - Management).
  yum:
    state: absent
    name: beegfs-mgmtd
  when: '"management" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS metadata package is uninstalled (RedHat/CentOS - Metadata).
  yum:
    state: absent
    name: beegfs-meta
  when: '"metadata" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS storage package is uninstalled (RedHat/CentOS - Storage).
  yum:
    state: absent
    name: beegfs-storage
  when: '"storage" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS infiniband package is uninstalled (RedHat/CentOS - Metadata/Storage).
  yum:
    state: absent
    name: libbeegfs-ib
  when: '("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles) and beegfs_enable_rdma'
  become: true

- name: Ensure the BeeGFS client package is uninstalled (RedHat/CentOS - Client).
  yum:
    state: absent
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
  when: '"client" in beegfs_node_roles'
  become: true

- name: Remove BeeGFS YUM repository (RedHat/CentOS).
  yum_repository:
    name: beegfs
    state: absent
    description: BeeGFS YUM Repo
    file: beegfs_rhel7
    baseurl: "{{ beegfs_rhel_repository_base_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ beegfs_rhel_repository_gpgkey }}"
  become: true
