- name: Ensure the BeeGFS management package is uninstalled (SUSE - Management).
  zypper:
    state: absent
    name: beegfs-mgmtd
  when: '"management" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS metadata package is uninstalled (SUSE - Metadata).
  zypper:
    state: absent
    name: beegfs-meta
  when: '"metadata" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS storage package is uninstalled (SUSE - Storage).
  zypper:
    state: absent
    name: beegfs-storage
  when: '"storage" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS infiniband package is uninstalled (SUSE - Metadata/Storage).
  zypper:
    state: absent
    name: libbeegfs-ib
  when: '("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles) and beegfs_enable_rdma'
  become: true

- name: Enable unsupported modules (SUSE - Client).
  replace:
    path: /etc/modprobe.d/10-unsupported-modules.conf
    regexp: 'allow_unsupported_modules 0'
    replace: 'allow_unsupported_modules 1'
  when: 'beegfs_allow_unsupported_module == True and "client" in beegfs_node_roles'
  become: true

- name: Ensure the BeeGFS client package is uninstalled (SUSE - Client).
  zypper:
    state: absent
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
  when: '"client" in beegfs_node_roles'
  become: true

- name: Add BeeGFS ZYPPER repository (SUSE).
  zypper_repository:
    name: beegfs
    state: absent
    description: BeeGFS ZYPPER Repo
    repo: "{{ beegfs_suse_repository_base_url }}"
    autorefresh: True
    auto_import_keys: True
  when: "'.repo' in beegfs_suse_repository_base_url"
  become: true

- name: Delete BeeGFS repo file (SUSE).
  file:
    state: absent
    path: "/etc/zypp/repos.d/beegfs.repo"
  when: "'.repo' not in beegfs_suse_repository_base_url"
  become: true
