namespace: "netapp_eseries"
name: "beegfs"
version: "3.2.0"
readme: "README.md"
authors:
  - "Vu Tran (@VuTran007)"
  - "Christian Whiteside (@mcwhiteside)"
  - "Joe McCormick (@iamjoemccormick)"
  - "Nathan Swartz (@swartzn)"
  - "Tracy Cummins (@tracycummins)"
description: "The NetApp E-Series BeeGFS collection provides roles to deploy supported versions of BeeGFS on hosts using NetApp E-Series storage."
license:
- "BSD-3-Clause"
tags:
  - netapp
  - eseries
  - santricity
  - beegfs
  - ha
dependencies:
  "netapp_eseries.santricity": '>=1.4.0'
  "netapp_eseries.host": ">=1.3.2"
repository: "https://github.com/netappeseries/beegfs/"
documentation: ""
homepage: "https://github.com/netappeseries/beegfs/"
issues: "https://github.com/netappeseries/beegfs/issues"
