- name: Ensure all cluster services are removed (SUSE - Management, Metadata, Storage).
  block:
    - name: Ensure the BeeGFS management package is uninstalled (SUSE - Management).
      community.general.zypper:
        state: absent
        name: beegfs-mgmtd
      register: beegfs_mgmtd_package
      when: '"management" in node_info["services"]'

    - name: Ensure the BeeGFS metadata package is uninstalled (SUSE - Metadata).
      community.general.zypper:
        state: absent
        name: beegfs-meta
      register: beegfs_meta_package
      when: '"metadata" in node_info["services"]'

    - name: Ensure the BeeGFS storage package is uninstalled (SUSE - Storage).
      community.general.zypper:
        state: absent
        name: beegfs-storage
      register: beegfs_storage_package
      when: '"storage" in node_info["services"]'

    - name: Ensure the BeeGFS infiniband package is uninstalled (SUSE - Metadata/Storage).
      community.general.zypper:
        state: absent
        name: libbeegfs-ib
      when: '("metadata" in node_info["services"] or "storage" in node_info["services"]) and node_info["service_configuration_options"]["connUseRDMA"] | default(true)'

    - name: Ensure ha-cluster-bootstrap is installed.
      community.general.zypper:
        state: absent
        name: pacemaker
      when: '"management" in node_info["services"] or "metadata" in node_info["services"] or "storage" in node_info["services"]'

    - name: Ensure ha-cluster-bootstrap is installed.
      community.general.zypper:
        state: absent
        name: corosync
      when: '"management" in node_info["services"] or "metadata" in node_info["services"] or "storage" in node_info["services"]'

    - name: Ensure ha-cluster-bootstrap is uninstalled.
      community.general.zypper:
        state: absent
        name: ha-cluster-bootstrap
      when: '"management" in node_info["services"] or "metadata" in node_info["services"] or "storage" in node_info["services"]'
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]
  become: true
