# stor_02 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8023
  connStoragePortUDP: 8023
  tuneBindToNumaZone: 0

floating_ips:
  - i2b:100.128.104.2/16
  - i1b:100.127.103.2/16

beegfs_service: storage 

beegfs_targets:
  ictad22a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s1_s2
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.5
            owning_controller: B          
          - size: 21.5
            owning_controller: B          
