# stor_09 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8013
  connStoragePortUDP: 8013
  tuneBindToNumaZone: 0

floating_ips:
  - i1b:100.127.103.9/16
  - i2b:100.128.104.9/16

beegfs_service: storage 

beegfs_targets:
  ictad22a03:
    eseries_storage_pool_configuration:
      - name: beegfs_s9_s10
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.5
            owning_controller: A          
          - size: 21.5
            owning_controller: A          
