# stor_05 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8053
  connStoragePortUDP: 8053
  tuneBindToNumaZone: 0

floating_ips:
  - i1b:100.127.103.5/16
  - i2b:100.128.104.5/16

beegfs_service: storage 

beegfs_targets:                             # Dictionary of E-Series storage systems that contain a list of storage pool definitions.
  ictad22a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s5_s6
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.5
            owning_controller: A          
          - size: 21.5
            owning_controller: A          