# stor_03 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8033
  connStoragePortUDP: 8033
  tuneBindToNumaZone: 1

floating_ips:
  - i3b:100.127.103.3/16
  - i4b:100.128.104.3/16

beegfs_service: storage 

beegfs_targets:
  ictad22a02:
    eseries_storage_pool_configuration:
      - name: beegfs_s3_s4
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.5
            owning_controller: A          
          - size: 21.5
            owning_controller: A          
