# stor_15 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8073
  connStoragePortUDP: 8073
  tuneBindToNumaZone: 1

floating_ips:
  - i3b:100.127.103.15/16
  - i4b:100.128.104.15/16

beegfs_service: storage 

beegfs_targets:
  ictad22a04:
    eseries_storage_pool_configuration:
      - name: beegfs_s15_s16
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.5
            owning_controller: A          
          - size: 21.5
            owning_controller: A          
