# stor_06 - BeeGFS HA Storage Resource Group
beegfs_ha_beegfs_storage_conf_resource_group_options:
  connStoragePortTCP: 8063
  connStoragePortUDP: 8063
  tuneBindToNumaZone: 0

floating_ips:
  - i2b:100.128.104.6/16
  - i1b:100.127.103.6/16

beegfs_service: storage 

beegfs_targets:
  ictad22a01:
    eseries_storage_pool_configuration:
      - name: beegfs_s5_s6
        raid_level: raid6
        criteria_drive_count: 10
        common_volume_configuration:
          segment_size_kb: 512
        volumes:
          - size: 21.5
            owning_controller: B          
          - size: 21.5
            owning_controller: B          