- name: Add required BeeGFS sysctl.conf entries.
  ansible.posix.sysctl:
    name: "{{ item['key'] }}"
    value: "{{ item['value'] }}"
    state: present
    reload: true
    sysctl_file: "{{ sysctl_conf_path }}"
  loop: "{{ lookup('dict', beegfs_ha_required_sysctl_entries) }}"
  become: true

- name: Determine all BeeGFS HA services.
  ansible.builtin.service_facts:
  changed_when: false
  become: true

- name: Disable SELinux and reboot nodes to apply changes.
  block:
    - name: Disable SELinux and reboot nodes to apply changes.
      ansible.builtin.include_role:
        name: netapp_eseries.host.selinux

    # It's important to ensure the cluster is started and in maintenance mode after a potential reboot.
    - name: Ensure BeeGFS HA cluster nodes are in maintenance mode.
      ansible.builtin.include_tasks: ../common/maintenance/set.yml
  when: eseries_beegfs_ha_disable_selinux
