- name: Add required BeeGFS sysctl.conf entries.
  ansible.posix.sysctl:
    name: "{{ item['key'] }}"
    value: "{{ item['value'] }}"
    state: present
    reload: true
    sysctl_file: "{{ sysctl_conf_path }}"
  loop: "{{ lookup('dict', beegfs_ha_required_sysctl_entries) }}"
  become: true

- name: Determine all BeeGFS HA services.
  ansible.builtin.service_facts:
  changed_when: false
  become: true

- name: Disable SELinux and reboot nodes to apply changes.
  block:
    - name: Check whether SELinux is enforced.
      ansible.builtin.shell: getenforce
      register: selinux_getenforce
      changed_when: false
      failed_when: selinux_getenforce["rc"] not in [0, 127]

    - name: Determine which cluster nodes that have SELinux enabled.
      ansible.builtin.set_fact:
        selinux_enabled_nodes: |-
          {%- set nodes = [] -%}
          {%- for node in ansible_play_hosts if hostvars[node]["selinux_getenforce"] is defined -%}
            {%- if hostvars[node]["selinux_getenforce"]["rc"] == 0
                   and hostvars[node]["selinux_getenforce"]["stdout"] != "Disabled" -%}
              {%- if nodes.append(node) -%}{%- endif -%}
            {%- endif -%}
          {%- endfor -%}
          {{- nodes -}}
      run_once: true

    - name: Ensure SELinux is configured to be disabled.
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=disabled

    - name: Fail when SELinux is disabled and a reboot is required but not permitted.
      ansible.builtin.fail:
        msg: "SELinux configuration had been disabled but requires a reboot to apply the new configuration
          (eseries_common_allow_host_reboot == false)! Please reboot and rerun the automation."
      when: inventory_hostname in selinux_enabled_nodes and not eseries_common_allow_host_reboot

    - name: Reboot host to apply SELinux configuration changes.
      ansible.builtin.include_role:
        name: netapp_eseries.host.common
        tasks_from: reboot.yml
        apply:
          vars:
            eseries_common_allow_host_reboot_reason: "SELinux configuration changed. Reboot is required."
      when: inventory_hostname in selinux_enabled_nodes

    - name: Ensure BeeGFS HA cluster nodes are in maintenance mode.
      ansible.builtin.include_tasks: ../common/maintenance/set.yml
      when: inventory_hostname == cluster_automation_node and selinux_enabled_nodes | length > 0
  when: eseries_beegfs_ha_disable_selinux
  become: true
