- name: Add NFS service to firewall zone "{{ nfs_firewall_rule['zone'] }}"
  ansible.posix.firewalld:
    service: "{{ nfs_firewall_rule['service'] }}"
    state: enabled
    offline: true
    permanent: "{{ nfs_firewall_rule['permanent'] }}"
    zone: "{{ nfs_firewall_rule['zone'] }}"
  become: true
  notify:
    - "Restart firewall daemon"
