# Ensure cluster attribute symmetric-cluster is set to false.
- name: Determine whether cluster is configured for asymmetric cluster architecture.
  command:
    cmd: "crm_attribute --type crm_config --name symmetric-cluster --query --quiet"
  changed_when: false
  failed_when: false
  register: symmetric_cluster_query
  become: true

- name: Set cluster to asymmetric cluster architecture.
  command:
    cmd: "crm_attribute --type crm_config --name symmetric-cluster --update false"
  register: symmetric_cluster_update
  when: symmetric_cluster_query['rc'] != 0 or symmetric_cluster_query['stdout'] != 'false'
  become: true


# Ensure cluster resource defaults are configured.
- name: Determine cluster resource defaults.
  command:
    cmd: "crm_attribute --type rsc_defaults --name {{ item['key'] }} --query --quiet"
  loop: "{{ beegfs_ha_cluster_resource_defaults | dict2items }}"
  changed_when: false
  failed_when: false
  register: resource_default_query
  become: true

- name: Set cluster resource defaults.
  command:
    cmd: "crm_attribute --type rsc_defaults --name {{ item['item']['key'] }} --update {{ item['item']['value'] }}"
  loop: "{{ resource_default_query['results'] }}"
  register: resource_default_update
  when: item['rc'] != 0 or item['stdout'] != item["item"]["value"] | string
  become: true


# Ensure pcs stonith-enabled property is configured as expected.
- name: Determine whether cluster is configured for asymmetric cluster architecture.
  command:
    cmd: "crm_attribute --type crm_config --name stonith-enabled --query --quiet"
  changed_when: false
  failed_when: false
  register: stonith_enabled_query
  become: true

- name: Set cluster to asymmetric cluster architecture.
  command:
    cmd: "crm_attribute --type crm_config --name stonith-enabled --update {{ beegfs_ha_enable_fence }}"
  register: symmetric_cluster_update
  when: stonith_enabled_query['rc'] != 0 or (stonith_enabled_query['stdout'] | bool) != beegfs_ha_enable_fence
  become: true
