- name: Ensure expected BeeGFS packages are installed (Always).
  include_tasks: "packages/{{ ansible_os_family | lower }}.yml"

- name: Ensure pcsd daemon is running and enabled.
  systemd:
    name: pcsd
    state: started
    enabled: true
  become: true
