- name: Create cluster_resource opening xml tag.
  set_fact:
    cluster_resources: "<resources>"

- name: Build pacemaker cluster management group resources.
  set_fact:
    cluster_resources: '{{ cluster_resources ~ lookup("template", "management/resources.j2") }}'

- name: Build pacemaker cluster metadata group resources.
  set_fact:
    cluster_resources: "{{ cluster_resources ~ lookup('template', 'metadata/resources.j2') }}"

- name: Build pacemaker cluster storage group resources.
  set_fact:
    cluster_resources: "{{ cluster_resources ~  lookup('template', 'storage/resources.j2') }}"

- name: Build pacemaker cluster fencing agent resources.
  set_fact:
    cluster_resources: "{{ cluster_resources ~ lookup('template', 'common/fencing_agent_resources.j2') }}"

- name: Create cluster_resource closing xml tag.
  set_fact:
    cluster_resources: "{{ cluster_resources }}</resources>"

- name: Query pacemaker resources.
  command:
    cmd: "cibadmin --query --scope resources"
  changed_when: false
  register: resources_query
  become: true

- name: Determine whether changes are required for pacemaker resources.
  set_fact:
    resources_change_required: |-
      {%- set existing = resources_query["stdout"] | default("") | regex_replace("\n", "") | regex_replace("\s+", " ") | regex_replace(">\s+<", "><") -%}
      {%- set expected = cluster_resources | regex_replace("\n", "") | regex_replace("\s+", " ") | regex_replace(">\s+<", "><") -%}
      {{- not (existing == expected) | bool -}}

- name: Update pacemaker resources.
  block:
    - name: Remove existing constraints.
      command:
        cmd: "cibadmin --replace --scope constraints --xml-text '<constraints/>'"
      become: true
    - name: Remove existing resources.
      command:
        cmd: "cibadmin --replace --scope resources --xml-text '<resources/>'"
      become: true
    - name: Update pacemaker resources.
      command:
        cmd: "cibadmin --replace --xpath '/cib/configuration/resources' --xml-text '{{ cluster_resources }}'"
      become: true
  when: resources_change_required

- name: Ensure BeeGFS HA cluster attributes are correct.
  include_tasks: attributes.yml

- name: Ensure BeeGFS HA services are running.
  include_tasks: constraints.yml
