- name: Check each pacemaker resource status.
  shell: "for x in $(crm_resource --list-raw); do crm_resource --resource=$x --why; done"
  register: pacemaker_resources_status
  changed_when: false
  failed_when: false
  become: true

- name: Determine whether any resources are not started.
  set_fact:
    resources_not_started: |-
      {%- set resources = [] -%}
      {%- for line in pacemaker_resources_status["stdout_lines"] if line and line | regex_search("is not running", ignorecase=True) -%}
        {%- if resources.append(line.split(" ")[1]) -%}{%- endif -%}
      {%- endfor -%}
      {{- resources -}}
    resources_not_started_retries: "{%- if resources_not_started_retries is not defined -%}1{%- else -%}{{ (resources_not_started_retries | int) + 1}}{%- endif -%}"

- name: Retry until resources are all started
  include_tasks: install/validate_resources.yml
  when: (resources_not_started_retries | int) < 10 and resources_not_started | length > 0
