- name: Set current storage system credentials
  include_role:
    name: netapp_eseries.santricity.nar_santricity_common
    tasks_from: build_info.yml
  when: inventory_hostname in groups[beegfs_ha_ansible_storage_group] and current_eseries_api_url is not defined

- name: Collect NetApp E-Series volume information (Always).
  include_tasks: ../collect_facts.yml

- name: Ensure pcs has been stopped
  command:
    cmd: "pcs cluster stop --force"
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]
  ignore_errors: true
  become: true

- name: Ensure pcs cluster has been destroyed
  command:
    cmd: "pcs cluster destroy --force"
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]
  ignore_errors: true
  become: true

- name: Ensure storage has been provisioned for hosts.
  include_role:
    name: netapp_eseries.host.unmount
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]
  vars:
    eseries_common_group: "{{ beegfs_ha_ansible_storage_group }}"
    eseries_unmount_volumes: all_volumes
    eseries_unmount_purge: true
    eseries_unmount_delete: true
    eseries_unmount_wipe_format_signatures: true

- name: Ensure multipath and iscsi protocol are setup.
  include_role:
    name: netapp_eseries.host.storage_setup
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]
  vars:
    eseries_storage_setup_uninstall: true

- name: Ensure storage has been provisioned for hosts.
  include_role:
    name: netapp_eseries.santricity.nar_santricity_host
  when: inventory_hostname in groups[beegfs_ha_ansible_storage_group]
  vars:
    eseries_remove_all_configuration: true

- name: Uninstall any configure OS-specific packages.
  include_tasks: "packages/{{ ansible_os_family | lower }}.yml"
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]

- name: Ensure any performance tuning has been removed.
  include_tasks: "performance_tuning.yml"
  when: 'inventory_hostname in groups[beegfs_ha_ansible_cluster_group] and ("metadata" in node_info["services"] or "storage" in node_info["services"])'

- name: Reboot nodes
  reboot:
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group] and beegfs_ha_uninstall_reboot | bool == True
  become: true

- name: Ensure any cluster and BeeGFS configuration files are removed.
  include_tasks: "configuration.yml"
  when: inventory_hostname in groups[beegfs_ha_ansible_cluster_group]
