- name: Ensure BeeGFS HA cluster is installed.
  import_tasks: install/main.yml

- name: Ensure BeeGFS HA cluster is uninstalled.
  include_tasks: uninstall/main.yml
  when: beegfs_ha_delete_data_and_uninstall_beegfs == True

