- name: "Gracefully shutdown {{ cluster_node }}."
  block:
    - name: "Place {{ cluster_node }} into standby."
      ansible.builtin.include_tasks: standby/set.yml

    - name: "Collect {{ cluster_node }} systemd service facts."
      service_facts:
      delegate_to: "{{ cluster_node }}"
      delegate_facts: true
      become: true

    - name: "Ensure pacemaker services are stopped and disabled on {{ cluster_node }}."
      ansible.builtin.systemd:
        state: stopped
        enabled: false
        name: pacemaker
      delegate_to: "{{ cluster_node }}"
      when: '"pacemaker.service" in (ansible_facts["services"].keys() | list)'

    - name: Ensure corosync services are stopped and disabled on all nodes marked for removal.
      ansible.builtin.systemd:
        state: stopped
        enabled: false
        name: corosync
      delegate_to: "{{ cluster_node }}"
      when: '"corosync.service" in (ansible_facts["services"].keys() | list)'
  when: cluster_node in (hostvars.keys() | list)

- name: Remove node from pacemaker
  ansible.builtin.command: "crm_node -R {{ cluster_node }} --force"
  changed_when: true
  delegate_to: "{{ cluster_automation_node }}"
  become: true
