- name: Configure BeeGFS Management Service.
  shell: "/opt/beegfs/sbin/beegfs-setup-mgmtd -p {{ beegfs_data_directory }}beegfs/mgmt/"
  register: beegfs_setup_mgmtd
  failed_when: "beegfs_setup_mgmtd.rc != 0 and 'ERROR: Storage directory is not empty.' not in beegfs_setup_mgmtd.stdout"
  changed_when: "'ERROR: Storage directory is not empty.' not in beegfs_setup_mgmtd.stdout"

- name: Ensure beegfs-mgmtd.conf is properly configured (Management).
  template:
    src: management/beegfs_management_conf.j2
    dest: "{{ beegfs_configuration_directory }}beegfs-mgmtd.conf"
  register: beegfs_mgmtd_service_conf

- name: Ensure beegfs-mgmtd-connInterfaces.conf is properly configured (Management).
  template:
    src: common/beegfs_connection_interfaces.j2
    dest: "{{ beegfs_configuration_directory }}beegfs-mgmtd-connInterfaces.conf"
    owner: root
    group: root
    mode: 0644
  register: beegfs_mgmtd_interfaces_conf

- name: Start BeeGFS Management Service.
  systemd:
    name: beegfs-mgmtd.service
    state: |-
      {%- if beegfs_setup_mgmtd.changed or beegfs_mgmtd_service_conf.changed or beegfs_mgmtd_interfaces_conf.changed %}
      restarted
      {%- else %}
      started
      {%- endif %}
    daemon-reload: yes
    enabled: yes
