- name: Configure BeeGFS Metadata Service.
  shell: "/opt/beegfs/sbin/beegfs-setup-meta -p {{ beegfs_data_directory }}beegfs/{{ item.name }} -m {{ beegfs_mgmt_node_ip }}"
  register: beegfs_setup_meta_result
  failed_when: "beegfs_setup_meta_result.rc != 0 and 'ERROR: Storage directory is not empty.' not in beegfs_setup_meta_result.stdout"
  changed_when: "'ERROR: Storage directory is not empty.' not in beegfs_setup_meta_result.stdout"
  loop: "{{ metadata_volumes }}"

- name: Ensure beegfs-meta-connInterfaces.conf is properly configured (Metadata).
  template:
    src: common/beegfs_connection_interfaces.j2
    dest: "{{ beegfs_configuration_directory }}beegfs-meta-connInterfaces.conf"
    owner: root
    group: root
    mode: 0644
  register: beegfs_meta_interfaces_conf

- name: Ensure beegfs-meta.conf is properly configured (Metadata).
  template:
    src: metadata/beegfs_meta_conf.j2
    dest: "{{ beegfs_configuration_directory }}beegfs-meta.conf"
  register: beegfs_meta_conf

- name: Override beegfs-meta.service systemd configuration to start service after remote-fs.target (Metadata).
  blockinfile:
    create: yes
    path: /etc/systemd/system/beegfs-meta.service.d/99-nar_santricity_beegfs_override.conf
    block: |
      [Unit]
      Requires=remote-fs.target
      After=remote-fs.target
  register: beegfs_meta_service_override

- name: Start BeeGFS Metadata Service.
  systemd:
    name: beegfs-meta.service
    state: |-
      {%- if beegfs_setup_meta_result.changed or beegfs_meta_interfaces_conf.changed or beegfs_meta_conf.changed or
             beegfs_meta_service_override.changed %}
      restarted
      {%- else %}
      started
      {%- endif %}
    daemon-reload: yes
    enabled: yes
