- name: Ensure the required firewall ports are open.
  firewalld:
    state: enabled
    permanent: true
    service: high-availability
  become: true
  when: beegfs_ha_allow_firewall_high_availability_service == True
