# BeeGFS client playbook. 

- hosts: beegfs_clients
  collections:
    - netapp_eseries.host
    - netapp_eseries.beegfs
  roles:
    - geerlingguy.ntp
  vars_files: "{{ playbook_dir | dirname }}/passwords.yml"
  become: False
  tasks:
    - name: Configure IPs for IPoIB ports
      import_role:
        name: ipoib

    - name: tune_performance
      import_role:
        name: tune_performance

    - name: Install BeeGFS client services
      import_role:
        name: beegfs_client
