- name: "Check whether {{ cluster_node }} is in standby mode."
  ansible.builtin.command: "crm_standby --node {{ cluster_node }} --query"
  register: standby_query
  failed_when: false
  changed_when: false
  become: true

- name: Move {{ cluster_node }} out of standby.
  block:
    - name: "Clear standby for {{ cluster_node }}."
      ansible.builtin.command: "crm_standby --node {{ cluster_node }} --delete"
      changed_when: true
  
    - name: "Wait for {{ cluster_node }} changes to stabilize."
      ansible.builtin.command: "crm_resource --wait"
      changed_when: false
  when: standby_query["stdout"] | regex_search(".*value=(true|on|y|1)", ignorecase=true)
  become: true

