# Note: If cluster_node variable is not specified then the inventory_hostname will be used.

- name: Check whether cluster nodes are in standby.
  ansible.builtin.command: "crm_standby --node {{ cluster_node | default(inventory_hostname) }} --query"
  register: standby_query
  failed_when: false
  changed_when: false
  become: true

- name: Ensure BeeGFS HA cluster nodes are in standby.
  block:
    - name: Ensure BeeGFS HA cluster nodes are in standby.
      ansible.builtin.command: "crm_standby --node {{ cluster_node | default(inventory_hostname) }} --update true"

    - name: Wait for cluster changes to stabilize.
      ansible.builtin.command: "crm_resource --wait"
      changed_when: false
  when: standby_query["rc"] in [0, 105] and standby_query["stdout"] | regex_search(".*value=(?!true|on|y|1)", ignorecase=true)
  become: true
