- name: Remove BeeGFS data directory at {{ beegfs_data_directory }}beegfs (Management/Metadata/Storage).
  file:
    path: "{{ beegfs_data_directory }}beegfs"
    state: absent
  when: '"management" in beegfs_node_roles or "storage" in beegfs_node_roles or "metadata" in beegfs_node_roles'

- name: Remove all files under {{ beegfs_configuration_directory }} (All).
  file:
    path: "{{ beegfs_configuration_directory }}"
    state: |-
      {%- if beegfs_configuration_directory is defined %}absent{%- endif %}

- name: Remove BeeGFS YUM repository (RedHat/CentOS).
  yum_repository:
    name: beegfs
    description: BeeGFS YUM Repo
    file: beegfs_rhel7
    baseurl: "{{ beegfs_rhel_repository_base_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ beegfs_rhel_repository_gpgkey }}"
    state: absent
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Remove BeeGFS apt key and repository (Debian/Ubuntu).
  shell: apt-key list | grep --regexp "BeeGFS" -B 1 | sed -n '1p' | sed 's/ //g'
  register: beegfs_id
  become: yes
  when: ansible_facts['os_family'] | lower == 'debian'
- apt_key:
    url: "{{ beegfs_debian_repository_gpgkey }}"
    state: absent
    id: "{{beegfs_id.stdout_lines[0]}}"
  become: yes
  when: ansible_facts['os_family'] | lower == 'debian'
- apt_repository:
    state: absent
    repo: "deb [arch=amd64] {{ beegfs_debian_repository_base_url }} stretch non-free"
    update_cache: yes
  become: yes
  when: ansible_facts['os_family'] | lower == 'debian'

- name: Remove BeeGFS ZYPPER repository (SUSE).
  zypper_repository:
    name: beegfs
    description: BeeGFS ZYPPER Repo
    repo: "{{ beegfs_suse_repository_base_url }}"
    autorefresh: True
    state: present
    auto_import_keys: True
  when: ansible_facts['os_family'] | lower == 'suse' and '.repo' in beegfs_suse_repository_base_url

- name: Remove BeeGFS repo file (SUSE).
  file:
    path: "/etc/zypp/repos.d/beegfs.repo"
    state: absent
  when:  ansible_facts['os_family'] | lower == 'suse' and '.repo' not in beegfs_suse_repository_base_url

- name: Remove BeeGFS sysctl.conf entries if performance tuning is enabled (Metadata/Storage).
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: absent
    reload: yes
    sysctl_file: "{%- if ansible_facts['os_family'] | lower == 'suse' %}/etc/sysctl.d/99-eseries-beegfs.conf{%- else %}/etc/sysctl.conf{%- endif %}"
  loop: "{{ lookup('dict', beegfs_sysctl_entries) }}"
  when: '"storage" in beegfs_node_roles or "metadata" in beegfs_node_roles'

- name: Delete /etc/sysctl.d/99-eseries-beegfs.conf file if performance tuning is enabled (SUSE - Metadata/Storage).
  file:
    path: "/etc/sysctl.d/99-eseries-beegfs.conf"
    state: absent
  when:  'ansible_facts["os_family"] | lower == "suse" and ("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles)'

- name: Delete udev rule at /etc/udev/rules.d/99-eseries-beegfs.rules if performance tuning is enabled (Metadata/Storage).
  file:
    path: "/etc/udev/rules.d/99-eseries-beegfs.rules"
    state: |-
      {%- if "/etc/udev/rules.d/99-eseries-beegfs.rules" is defined %}absent{%- endif %}
  when: '"storage" in beegfs_node_roles or "metadata" in beegfs_node_roles'