- name: Purge pcs configuration directory.
  ansible.builtin.file:
    state: absent
    path: "{{ beegfs_ha_uninstall_pcsd_dir }}"
  become: true
  when: beegfs_ha_management_tool == 'pcs'

- name: Purge pacemaker configuration directory.
  ansible.builtin.file:
    state: absent
    path: "{{ beegfs_ha_uninstall_pacemaker_cib_dir }}"
  become: true

- name: Purge BeeGFS service overides.
  ansible.builtin.file:
    state: absent
    path: "/etc/systemd/system/beegfs-{{ item }}.service"
  loop: ['mgmtd', 'meta@', 'storage@']
  become: true
