- name: Remove BeeGFS performance sysctl.conf entries if performance tuning is enabled (Metadata/Storage).
  sysctl:
    name: "{{ item['key'] }}"
    value: "{{ item['value'] }}"
    state: absent
    reload: true
    sysctl_file: "{{ sysctl_conf_path }}"
  loop: "{{ lookup('dict', beegfs_ha_performance_sysctl_entries) }}"
  become: true

- name: Delete /etc/sysctl.d/99-eseries-beegfs.conf file if performance tuning is enabled.
  ansible.builtin.file:
    path: "{{ sysctl_conf_path }}"
    state: absent
  become: true

- name: Delete udev rule at /etc/udev/rules.d/99-eseries-beegfs.rules if performance tuning is enabled (Metadata/Storage).
  ansible.builtin.file:
    path: "/etc/udev/rules.d/99-eseries-beegfs.rules"
    state: absent
  become: true
