# Ensure cluster crm_config defaults are configured.
- name: Determine all global configuration attributes.
  ansible.builtin.command: "cibadmin --query --scope crm_config"
  changed_when: false
  register: crm_config
  become: true

- name: Delete any unexpected global configuration attributes.
  ansible.builtin.command: "crm_attribute --type crm_config --name {{ item }} --delete --quiet"
  loop: "{{ attributes }}"
  become: true
  vars:
    attributes: |-
      {%- set attributes = [] -%}
      {%- for line in crm_config["stdout_lines"] -%}
        {%- set results = line | regex_search(' *<nvpair.*name="(?P<name>.*?)"', '\\g<name>') -%}
        {%- if results is iterable and results[0] not in (beegfs_ha_cluster_crm_config_defaults.keys() | list) + (beegfs_ha_cluster_crm_config_options.keys() | list) + beegfs_ha_cluster_crm_config_ignore -%}
          {%- if attributes.append(results[0]) -%}{%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {{- attributes -}}

- name: Get the current global configuration attributes.
  ansible.builtin.command: "crm_attribute --type crm_config --name {{ item['key'] }} --query --quiet"
  loop: "{{ lookup('ansible.builtin.dict', beegfs_ha_cluster_crm_config_defaults | combine(beegfs_ha_cluster_crm_config_options)) }}"
  changed_when: false
  failed_when: false
  register: crm_config_defaults_query
  become: true

- name: Set global configuration attributes
  ansible.builtin.command: "crm_attribute --type crm_config --name {{ item['item']['key'] }} --update {{ item['item']['value'] }}"
  loop: "{{ crm_config_defaults_query['results'] }}"
  when: item['rc'] != 0 or item['stdout'] != item["item"]["value"] | string
  become: true

# Ensure cluster resource defaults are configured.
- name: Determine cluster resource defaults.
  ansible.builtin.command: "crm_attribute --type rsc_defaults --name {{ item['key'] }} --query --quiet"
  loop: "{{ lookup('ansible.builtin.dict', beegfs_ha_cluster_resource_defaults, wantlist=true) }}"
  changed_when: false
  failed_when: false
  register: resource_default_query
  become: true

- name: Set cluster resource defaults.
  ansible.builtin.command: "crm_attribute --type rsc_defaults --name {{ item['item']['key'] }} --update {{ item['item']['value'] }}"
  loop: "{{ resource_default_query['results'] }}"
  when: item['rc'] != 0 or item['stdout'] != item["item"]["value"] | string
  become: true
