- name: Ensure the required firewall ports are open.
  include_tasks: ../common/firewall/install.yml

- name: Ensure the ntp is configured.
  include_tasks: common/ntp.yml
  when: beegfs_ha_ntp_enabled == true or beegfs_ha_chrony_enabled == true

- name: Configure common cluster node configurations.
  include_tasks: common/nodes.yml

- name: Ensure the cluster is built (Cluster nodes only).
  include_tasks: common/build_cluster.yml

- name: "Ensure cluster configuration tool ({{ beegfs_ha_management_tool }}) is configured (Cluster and remote nodes)."
  include_tasks: "common/{{ beegfs_ha_management_tool }}.yml"
  when: beegfs_ha_management_tool is defined and beegfs_ha_management_tool
