- name: Ensure the required firewall ports are open.
  include_tasks: common/firewall.yml

- name: Ensure the ntp is configured.
  include_tasks: common/ntp.yml

- name: Ensure /etc/hosts file is populated with cluster nodes and floating IP addresses.
  include_tasks: common/hosts.yml

- name: Ensure the cluster is built.
  include_tasks: common/build_cluster.yml

- name: "Ensure cluster configuration tool ({{ beegfs_ha_management_tool }}) is configured."
  include_tasks: "common/{{ beegfs_ha_management_tool }}.yml"
