- name: "Clear any previous failures for {{ item['key'] }}-group resource."
  ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-group --clear"
  register: clear_resource_group_failures
  failed_when: clear_resource_group_failures["rc"] != 0
  changed_when: true
  become: true

- name: "Clear any previous failures for {{ item['key'] }}-monitor resource."
  ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-monitor --clear"
  register: clear_resource_monitor_failures
  failed_when: clear_resource_monitor_failures["rc"] != 0
  changed_when: true
  become: true

# If the resource was moved to the preferred node after we made the list of move_resources we'll get an error:
#   `crm_resource: Error performing operation: Requested item already exists' which we ignore. 
#   This is not unusual if the cluster was stopped when we ran the role. 
- name : "Move {{ item['key'] }} resource to its preferred node [{{ item['value'] }}]"
  ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-monitor --move --node {{ item['value'] }}"
  register: move_resource
  failed_when: 'move_resource["rc"] != 0 and move_resource["stderr"] != "crm_resource: Error performing operation: Requested item already exists"'
  changed_when: true
  become: true

- name: "Wait for {{ item['key'] }} resource to move to its preferred node [{{ item['value'] }}]"
  ansible.builtin.command: "crm_resource --wait"
  changed_when: false

- name : "Clear {{ item['key'] }} resource move constraint."
  ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-monitor --clear"
  register: move_resource
  failed_when: move_resource["rc"] != 0
  changed_when: true
  become: true
