# Clear any previous failures.
- name: "Clear previous {{ item['key'] }}-group failures."
  block:
    - name: "Clear previous {{ item['key'] }}-group failures."
      ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-group --clear"

    - name: "Clear any previous {{ item['key'] }}-monitor failures."
      ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-monitor --clear"

    - name: "Wait for cluster to stabilize."
      ansible.builtin.command: "crm_resource --wait"
  become: true

# Move resources back to their preferred nodes.
- name: Determine {{ item['key'] }}-monitor resource location.
  ansible.builtin.command: "crm_resource --locate --resource {{ item['key'] }}-monitor --quiet"
  register: resource_location
  changed_when: false
  become: true

- name: "Move {{ item['key'] }}-monitor resource back to {{ item['value'] }}."
  block:
    - name: "Move {{ item['key'] }}-monitor resource back to {{ item['value'] }}."
      ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-monitor --move --node {{ item['value'] }}"

    - name: "Wait for cluster to stabilize."
      ansible.builtin.command: "crm_resource --wait"

    - name : "Clear resource move constraints."
      ansible.builtin.command: "crm_resource --resource {{ item['key'] }}-monitor --clear"
  when: resource_location['stdout'] != item['value']
  become: true
