---
- name: Set facts for beegfs-remote configurations.
  ansible.builtin.set_fact:
    beegfs_remote_config: "{{ beegfs_remote_config_defaults | combine(beegfs_remote_config_options) }}"

- name: Set facts for BeeGFS TLS configurations.
  ansible.builtin.set_fact:
    beegfs_remote_tls_cert_dest_path: "{{ beegfs_remote_config['server']['tls-cert-file'] }}"
    beegfs_remote_tls_key_dest_path: "{{ beegfs_remote_config['server']['tls-key-file'] }}"
