- name: Add BeeGFS YUM repository (RedHat/CentOS).
  yum_repository:
    name: beegfs
    description: BeeGFS YUM Repo
    file: beegfs_rhel7
    baseurl: "{{ beegfs_rhel_repository_base_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ beegfs_rhel_repository_gpgkey }}"

- name: Get kernel version (RedHat/CentOS - Client).
  shell: "uname -r"
  register: shell_output
  failed_when: "shell_output.rc != 0"
  changed_when: False
  when: '"client" in beegfs_node_roles'

- name: Ensure kernel-devel is installed (RedHat/CentOS - Client).
  yum:
    name: "kernel-devel-{{ shell_output.stdout_lines[0] }}"
  when: '"client" in beegfs_node_roles'

- name: Ensure the BeeGFS management package is installed (RedHat/CentOS - Management).
  yum:
    state: |-
      {%- if beegfs_force_beegfs_upgrade %}latest{%- else %}present{%- endif %}
    name: beegfs-mgmtd
  when: '"management" in beegfs_node_roles'

- name: Ensure the BeeGFS metadata package is installed (RedHat/CentOS - Metadata).
  yum:
    state: |-
      {%- if beegfs_force_beegfs_upgrade %}latest{%- else %}present{%- endif %}
    name:
      - beegfs-meta
  when: '"metadata" in beegfs_node_roles'

- name: Ensure the BeeGFS storage package is installed (RedHat/CentOS - Storage).
  yum:
    state: |-
      {%- if beegfs_force_beegfs_upgrade %}latest{%- else %}present{%- endif %}
    name:
      - beegfs-storage
  when: '"storage" in beegfs_node_roles'

- name: Ensure the BeeGFS infiniband package is installed (RedHat/CentOS - Metadata/Storage).
  yum:
    state: |-
      {%- if beegfs_force_beegfs_upgrade %}latest{%- else %}present{%- endif %}
    name: libbeegfs-ib
  when: '("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles) and beegfs_enable_rdma'

- name: Ensure the BeeGFS client package is installed (RedHat/CentOS - Client).
  yum:
    state: |-
      {%- if beegfs_force_beegfs_upgrade %}latest{%- else %}present{%- endif %}
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
  when: '"client" in beegfs_node_roles'

- name: Ensure NTP is installed (RedHat/CentOS).
  yum:
    state: latest
    name: ntp
  when: beegfs_ntp_enabled == True

- name: Ensure Chrony is uninstalled (RedHat/CentOS).
  yum:
    state: absent
    name: chrony
  when: beegfs_ntp_enabled == True
