ansible_host: "<MANAGEMENT_IP>"

eseries_ipoib_interfaces:
  - name: i1b
    address: 100.127.100.3/16
  - name: i4b
    address: 100.128.100.3/16

beegfs_ha_cluster_node_ips:
  - <MANAGEMENT_IP>
  - 100.127.100.3
  - 100.128.100.3

# NVMe over InfiniBand storage communication protocol information
eseries_nvme_ib_interfaces:
  - name: i1a
    address: 192.168.1.10/24
    configure: true
  - name: i2a
    address: 192.168.3.10/24
    configure: true
  - name: i3a
    address: 192.168.5.10/24
    configure: true
  - name: i4a
    address: 192.168.7.10/24
    configure: true

