- name: Ensure software properties common package is installed (Debian/Ubuntu).
  ansible.builtin.apt:
    state: present
    name: software-properties-common

- name: Configure package manager (Debian/Ubuntu).
  ansible.builtin.include_tasks: debian_package_manager.yml

# At least when installing the DKMS version it will skip the module build if the kernel headers aren't installed.
- name: Get kernel version (Debian/Ubuntu).
  ansible.builtin.command: "uname -r"
  register: shell_output
  failed_when: "shell_output.rc != 0"
  changed_when: false

- name: Ensure linux-headers-{{ shell_output.stdout_lines[0] }} is installed (Debian/Ubuntu).
  ansible.builtin.apt:
    name: "linux-headers-{{ shell_output.stdout_lines[0] }}"

- name: Ensure BeeGFS client package is installed (Debian/Ubuntu - Client).
  ansible.builtin.apt:
    state: |-
      {%- if beegfs_client_force_upgrade %}latest{%- else %}present{%- endif %}
    name:
      - "{%- if beegfs_client_dkms_install %}beegfs-client-dkms{%- else %}beegfs-client{%- endif %}"
      - "{%- if beegfs_tls_enabled is not defined %}beegfs-helperd{%- else %}beegfs-tools{%- endif %}"
      - beegfs-utils
      - libelf-dev
  register: package_mgr_result

- name: Ensure packages required for NVIDIA GPUDirect Storage is installed (Debian/Ubuntu).
  ansible.builtin.apt:
    state: present
    name: "{{ beegfs_client_gds_packages }}"
  when: beegfs_client_gds_support | bool
