---
- name: Mount BeeGFS  # We wrap things in a block to ensure the tags work right with include_tasks.
  vars:
    generated_conf_prefix: |-
      {%- set mgmt_ip = item['sysMgmtdHost'] -%}
      {%- if item['beegfs_client_config']['connClientPortUDP'] is defined -%}
        {{- mgmt_ip }}_{{ item['beegfs_client_config']['connClientPortUDP'] -}}
      {%- else -%}
        {{- mgmt_ip -}}
      {%- endif -%}
    client_conf_path: "/etc/beegfs/{{ generated_conf_prefix }}_beegfs-client.conf"
    connInterfaces_path: |-
      {%- if item['beegfs_client_config']['connInterfacesFile'] is defined -%}
        {{- item['beegfs_client_config']['connInterfacesFile'] -}}
      {%- elif item['connInterfaces'] is defined -%}
        /etc/beegfs/{{ generated_conf_prefix }}_client-rdma.conf
      {%- endif -%}
    connRDMAInterfacesFile_path: |-
      {%- if item['beegfs_client_config']['connRDMAInterfacesFile'] is defined -%}
        {{- item['beegfs_client_config']['connRDMAInterfacesFile'] -}}
      {%- elif item['connInterfaces'] is defined -%}
        /etc/beegfs/{{ generated_conf_prefix }}_connInterfaces.conf
      {%- endif -%}
    connAuthFile_src: |-
      {%- if item['connAuthFile_src'] is defined -%}
        {{- item['connAuthFile_src'] -}}
      {%- elif item['connAuthFile_secret'] is not defined -%}
        {{- beegfs_client_connAuthFile_src -}}
      {%- endif -%}
    connAuthFile_secret: |-
      {%- if item['connAuthFile_secret'] is defined -%}
        {{- item['connAuthFile_secret'] -}}
      {%- elif item['connAuthFile_src'] is not defined -%}
        {{- beegfs_client_connAuthFile_secret -}}
      {%- endif -%}
    connAuthFile_dest: |-
      {%- if item['beegfs_client_config']['connAuthFile'] is defined -%}
        {{- item['beegfs_client_config']['connAuthFile'] -}}
      {%- else -%}
        /etc/beegfs/{{ item['sysMgmtdHost'] }}_connAuthFile
      {%- endif -%}
    connAuthFile_enabled: "{{ item['connAuthFile_enabled'] | default(beegfs_client_connAuthFile_enabled) }}"

  block:
    - name: Verify only one connection authentication method is chosen.
      ansible.builtin.fail:
        msg: |
          Only one connection authentication method maybe chosen for each mount! Each mount may only specify one of the
          following options: connAuthFile_src or connAuthFile_secret
      when: connAuthFile_src and connAuthFile_secret

    - name: Ensure BeeGFS connection authentication file exists copied from source file.
      ansible.builtin.copy:
        src: "{{ connAuthFile_path }}"
        dest: "{{ connAuthFile_dest }}"
        mode: "0400"
      when: connAuthFile_enabled and connAuthFile_path
      notify:
        - Restart BeeGFS Client
      vars:
        connAuthFile_path: |-
          {%- if not connAuthFile_secret -%}
            {%- if connAuthFile_src -%}
              {{- connAuthFile_src -}}
            {%- else -%}
              {{- playbook_dir }}/files/beegfs/{{ item['sysMgmtdHost'] }}_connAuthFile
            {%- endif -%}
          {%- endif -%}

    - name: Ensure BeeGFS connection authentication file exists with provided secret.
      ansible.builtin.copy:
        content: "{{ connAuthFile_secret }}"
        dest: "{{ connAuthFile_dest }}"
        mode: "0400"
      when: connAuthFile_enabled and connAuthFile_secret
      notify:
        - Restart BeeGFS Client

    - name: Create/populate the connInterfaces file at {{ connInterfaces_path }}.
      ansible.builtin.template:
        src: beegfs_connection_interfaces.j2
        dest: "{{ connInterfaces_path }}"
        mode: 0644
      notify:
        - Restart BeeGFS Client

    - name: Create/populate the connRDMAInterfaces file at {{ connRDMAInterfacesFile_path }}.
      ansible.builtin.template:
        src: beegfs_connection_interfaces.j2
        dest: "{{ connRDMAInterfacesFile_path }}"
        mode: 0644
      notify:
        - Restart BeeGFS Client

    - name: Generate the BeeGFS client configuration file for this mount point.
      netapp_eseries.host.update_conf:
        src: /etc/beegfs/beegfs-client.conf
        dest: "{{ client_conf_path }}"
        options: |-
          {%- set required_options = {'sysMgmtdHost': item['sysMgmtdHost']} -%}
          {%- if connInterfaces_path -%}
            {%- if required_options.update({'connInterfacesFile': connInterfaces_path}) -%}{%- endif -%}
          {%- endif -%}
          {%- if beegfs_client_multirail_support -%}
            {%- if required_options.update({'connRDMAInterfacesFile': connRDMAInterfacesFile_path}) -%}{%- endif -%}
          {%- endif -%}
          {%- if connAuthFile_enabled -%}
            {%- if required_options.update({'connAuthFile': connAuthFile_dest}) -%}{%- endif -%}
          {%- endif -%}
          {{- beegfs_client_config_default_options | combine(item['beegfs_client_config']) | combine(required_options) -}}
        mode: "0644"
      notify:
        - Restart BeeGFS Client

    - name: Mount BeeGFS (DKMS client).
      block:
        - name: Mount BeeGFS and add entry to /etc/fstab.
          ansible.posix.mount:
            path: "{{ item['mount_point'] }}"
            src: beegfs_nodev
            fstype: beegfs
            opts: "rw,relatime,cfgFile={{ client_conf_path }},_netdev,x-systemd.after=beegfs-helperd"
            state: "{%- if item['mounted'] is defined and item['mounted'] == False  %}unmounted{%- else %}mounted{%- endif %}"
      when: beegfs_client_dkms_install

  tags: beegfs_client_mount
