- name: 
  block:
    - name: Move cluster nodes into maintenance mode.
      ansible.builtin.include_tasks: set_node.yml
      loop: "{{ groups[beegfs_ha_ansible_cluster_group] }}"
      loop_control:
        loop_var: cluster_node

    - name: Wait for cluster changes to stabilize if the cluster is started.
      ansible.builtin.command: "crm_resource --wait"
      changed_when: false
      register: crm_resource_wait_result
      failed_when: "crm_resource_wait_result.rc != 0 and 'crm_resource: Could not connect to the CIB: Transport endpoint is not connected' not in crm_resource_wait_result.stderr"

  run_once: true

