- name: Stop BeeGFS Client
  ansible.builtin.systemd:
    name: beegfs-client
    state: stopped
  listen: "Restart BeeGFS Client"
  when: not beegfs_client_dkms_install
  become: true

# This task will capture all BeeGFS mounts whereas if beegfs_client_mounts variable is relied on, it is possible for
#   other BeeGFS mounts to remain (i.e. removed from inventory, manually configured, etc). This is problematic since any
#   BeeGFS mount will prevent the beegfs module from being unloaded.
- name: Retrieve all BeeGFS mounts.
  ansible.builtin.command: egrep "^beegfs_nodev" /proc/mounts
  register: beegfs_proc_mounts
  failed_when: beegfs_proc_mounts["rc"] not in [0, 1]
  changed_when: false
  listen: "Restart BeeGFS Client"
  become: true

- name: Ensure all mounts are removed
  ansible.builtin.mount:
    state: unmounted
    path: "{{ item }}"
  loop: "{{ mounts }}"
  listen: "Restart BeeGFS Client"
  become: true
  vars:
    mounts: |-
      {%- set mounts = [] -%}
      {%- for line in beegfs_proc_mounts["stdout_lines"] -%}
        {%- set parts = line | ansible.builtin.split(" ") -%}
        {%- if parts | length > 2 -%}
          {%- if mounts.append(parts[1]) -%}{%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {{- mounts -}}

- name: Ensure the beegfs module is removed.
  ansible.builtin.modprobe:
    state: absent
    name: beegfs
  listen: "Restart BeeGFS Client"
  become: true

- name: Stop BeeGFS Helper
  ansible.builtin.systemd:
    name: beegfs-helperd
    state: stopped
  listen: "Restart BeeGFS Client"
  when: not beegfs_client_dkms_install
  become: true

- name: Start BeeGFS Helper
  ansible.builtin.systemd:
    name: beegfs-helperd
    state: started
  listen: "Restart BeeGFS Client"
  when: not beegfs_client_dkms_install
  become: true

- name: Start BeeGFS Client
  ansible.builtin.systemd:
    name: beegfs-client
    state: started
  listen: "Restart BeeGFS Client"
  when: not beegfs_client_dkms_install
  become: true
