- name: Open TCP/UDP Firewall Ports for the BeeGFS Management Service.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  when: '"management" in beegfs_node_roles'
  loop:
    - "8008/tcp"
    - "8008/udp"

- name: Open TCP/UDP Firewall Ports for the BeeGFS Storage Service.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  when: '"storage" in beegfs_node_roles'
  loop:
    - "8003/tcp"
    - "8003/udp"

- name: Open TCP/UDP Firewall Ports for the BeeGFS Metadata Service.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  when: '"metadata" in beegfs_node_roles'
  loop:
    - "8005/tcp"
    - "8005/udp"

- name: Open UDP Firewall Port for the BeeGFS Client Service.
  firewalld:
    port: 8004/udp
    permanent: yes
    state: enabled
    immediate: yes
  when: '"client" in beegfs_node_roles'
