- name: Format BeeGFS Storage volumes using xfs (Storage).
  filesystem:
    fstype: xfs
    dev: "{{ item['path'] }}"
    opts: "-d su={{ item['segment_size_kb'] }}k,sw={{ item['stripe_count'] }} -l version=2,su={{ item['segment_size_kb'] }}k"
  loop: "{{ lookup('list', storage_volumes) }}"
  when: "'storage' in beegfs_node_roles"

- name: Format BeeGFS Metadata volumes using ext4.
  filesystem:
    fstype: ext4
    dev: "{{ item['path'] }}"
    opts: "{{ beegfs_metadata_format_options }}"
  loop: "{{ lookup('list', metadata_volumes) }}"
  when: "'metadata' in beegfs_node_roles"

- name: Mount BeeGFS Storage volumes (quotas disabled).
  mount:
    path: "{{ beegfs_data_directory }}beegfs/{{ item['name'] }}"
    src: "{{ item['path'] }}"
    fstype: xfs
    state: mounted
    opts: "{{ beegfs_storage_mounting_options }}"
  loop: "{{ lookup('list', storage_volumes) }}"
  when: "'storage' in beegfs_node_roles and beegfs_enable_quota != True"

- name: Mount BeeGFS Storage volumes (quotas enabled).
  mount:
    path: "{{ beegfs_data_directory }}beegfs/{{ item['name'] }}"
    src: "{{ item['path'] }}"
    fstype: xfs
    state: mounted
    opts: "{{ beegfs_storage_mounting_options_quotas }}"
  loop: "{{ lookup('list', storage_volumes) }}"
  when: "'storage' in beegfs_node_roles and beegfs_enable_quota == True"

- name: Mount BeeGFS Metadata volumes.
  mount:
    path: "{{ beegfs_data_directory }}beegfs/{{ item['name'] }}"
    src: "{{ item['path'] }}"
    fstype: ext4
    state: mounted
    opts: "{{ beegfs_metadata_mounting_options }}"
  loop: "{{ lookup('list', metadata_volumes) }}"
  when: "'metadata' in beegfs_node_roles"
