- name: Create udev rule at /etc/udev/rules.d/99-eseries-beegfs.rules (Storage/Metadata).
  template:
    src: common/eseries_beegfs_udev_rule.j2
    dest: "/etc/udev/rules.d/99-eseries-beegfs.rules"
  register: beegfs_udev_rule_result

- name: Reload udev rules (Storage/Metadata).
  command: udevadm control --reload
  when: beegfs_udev_rule_result.changed == True

- name: Trigger updated udev rules (Storage/Metadata).
  command: udevadm trigger
  when: beegfs_udev_rule_result.changed == True

- name: Add BeeGFS sysctl.conf entries (Storage/Metadata).
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: "{%- if ansible_facts['os_family'] | lower == 'suse' %}/etc/sysctl.d/99-eseries-beegfs.conf{%- else %}/etc/sysctl.conf{%- endif %}"
  loop: "{{ lookup('dict', beegfs_sysctl_entries) }}"