- name: Check that multipathd is started/enabled on BeeGFS storage/metadata nodes.
  systemd:
    name: multipathd.service
    state: started
    enabled: yes
  check_mode: yes
  when: '"storage" in beegfs_node_roles or "metadata" in beegfs_node_roles'
  register: check_multipath_result

- name: Check that multipathd is started/enabled on BeeGFS storage/metadata nodes.
  fail:
    msg: "Multipathing is not started/enabled on one or more hosts designated as BeeGFS storage or metadata nodes. Please see the README file for a full list of prerequisites."
  when: check_multipath_result.changed

- name: Check if any hosts have more than one volume mapped with the workload tag beegfs_metadata.
  fail:
    msg: "BeeGFS only supports a single metadata target at this time. More than one volume is mapped to this host with the workload tag beegfs_metadata. With this configuration we have no way to determine what volume to use for BeeGFS metadata."
  when: '"metadata" in beegfs_node_roles and (metadata_volumes is defined and metadata_volumes|length > 1)'

- name: Verify beegfs_data_directory path ends in a forward slash.
  fail:
    msg: "Warning the beegfs_data_directory variable must end in a forward slash (example: /data/beegfs/). Current value: '{{ beegfs_data_directory }}'."
  when: 'beegfs_data_directory[-1] != "/"'

- name: Verify beegfs_node_roles contains valid node types.
  fail:
    msg: "The beegfs_node_roles variable for this host contains an unsupported node type. Supported values: 'management', 'metadata', 'storage', 'client'. Current values: '{{ beegfs_node_roles }}'."
  when: "item not in ['management', 'metadata', 'storage', 'client']"
  loop: "{{ beegfs_node_roles }}"
