- name: Uninstall any configure OS-specific client packages.
  include_tasks: "../packages/{{ ansible_os_family | lower }}_client_only.yml"

- name: Ensure beegfs-client.conf is properly configured (Client).
  file:
    state: absent
    path: "{{ beegfs_ha_client_configuration_directory }}beegfs-client.conf"
  become: true

- name: Ensure beegfs-client-connInterfaces.conf is properly configured (Client).
  file:
    state: absent
    path: "{{ beegfs_ha_client_configuration_directory }}beegfs-client-connInterfaces.conf"
  become: true

- name: Ensure beegfs-client-autobuild.conf is properly configured (Client).
  file:
    state: absent
    path: "{{ beegfs_ha_client_configuration_directory }}beegfs-client-autobuild.conf"
  become: true
