# Only place variables that are required for the OS-family. These variables cannot be overridden by the user's inventory.
beegfs_ha_management_tool: pcs
beegfs_ha_ntp_service: ntp.service
beegfs_ha_chrony_service: chronyd.service
sysctl_conf_path: "/etc/sysctl.d/99-eseries-beegfs.conf"
