- name: Add BeeGFS ZYPPER repository (SUSE).
  zypper_repository:
    name: beegfs
    description: BeeGFS ZYPPER Repo
    repo: "{{ beegfs_ha_suse_repository_base_url }}"
    autorefresh: True
    state: present
    auto_import_keys: True
  when: "'.repo' in beegfs_ha_suse_repository_base_url"
  become: true

- name: Create BeeGFS repo file (SUSE).
  template:
    src: common/suse_repo.j2
    dest: "/etc/zypp/repos.d/beegfs.repo"
  when: "'.repo' not in beegfs_ha_suse_repository_base_url"
  become: true

- name: Configure packages for BeeGFS clients (SUSE - Client).
  block:
    - name: Enable unsupported modules (SUSE - Client).
      replace:
        path: /etc/modprobe.d/10-unsupported-modules.conf
        regexp: 'allow_unsupported_modules 0'
        replace: 'allow_unsupported_modules 1'
      when: beegfs_ha_suse_allow_unsupported_module == True

    - name: Get kernel version (SUSE - Client).
      shell: "uname -r | cut -f 1,2 -d \"-\""
      register: uname_shell_output
      failed_when: "uname_shell_output['rc'] != 0"
      changed_when: false

    - name: Ensure kernel-devel is installed (SUSE - Client).
      zypper:
        name: "kernel-devel={{ uname_shell_output['stdout_lines'][0] }}"
        state: present

    - name: Ensure kernel-default-devel is installed (SUSE - Client).
      zypper:
        name: "kernel-default-devel={{ uname_shell_output['stdout_lines'][0] }}"
        state: present

    - name: Ensure kernel-source is installed (SUSE - Client).
      zypper:
        name: "kernel-source={{ uname_shell_output['stdout_lines'][0] }}"
        state: present

    - name: Ensure the BeeGFS client package is installed (SUSE - Client).
      zypper:
        state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
        name:
          - "beegfs-client={{ beegfs_ha_beegfs_version }}"
          - "beegfs-helperd={{ beegfs_ha_beegfs_version }}"
          - "beegfs-utils={{ beegfs_ha_beegfs_version }}"
  when: beegfs_ha_client == True
  become: true

- name: Ensure NTP is installed (SUSE).
  zypper:
    state: latest
    name: ntp
  when: beegfs_ntp_enabled | bool == True
  become: true

- name: Ensure Chrony is uninstalled (SUSE).
  zypper:
    state: absent
    name: chrony
  when: beegfs_ntp_enabled | bool == True
  become: true
