- name: Stop BeeGFS management service.
  systemd:
    name: beegfs-mgmtd.service
    state: stopped
  when: "'beegfs-mgmtd.service' in (ansible_facts['services'].keys() | list)"
  become: true

- name: Remove the BeeGFS management directory at {{ beegfs_data_directory }}beegfs/mgmt.
  file:
    path: "{{ beegfs_data_directory }}beegfs/mgmt"
    state: absent
  become: true

- name: Close BeeGFS management service TCP/UDP firewall ports if configured by the role.
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: disabled
    immediate: yes
  when: beegfs_open_firewall_ports == True
  loop:
    - "8008/tcp"
    - "8008/udp"
  become: true
