- name: Set global variables.
  ansible.builtin.set_fact:
    eseries_common_firewall_configure: "{{ beegfs_ha_firewall_configure }}"

- name: Ensure BeeGFS HA cluster is installed.
  import_tasks: install/main.yml

- name: Ensure BeeGFS HA cluster is uninstalled.
  include_tasks: uninstall/main.yml
  when: beegfs_ha_uninstall == True
