- name: "Check whether {{ cluster_node }} is in maintenance mode."
  ansible.builtin.command: "crm_attribute --node {{ cluster_node }} --name maintenance --query"
  register: maintenance_query
  failed_when: false
  changed_when: false
  delegate_to: "{{ cluster_automation_node }}"
  become: true

- name: Restart pacemaker on {{ cluster_node }}
  ansible.builtin.command: systemctl restart pacemaker
  become: true
  delegate_to: "{{ cluster_node }}"
  when: maintenance_query["stdout"] | regex_search(beegfs_ha_common_pacemaker_true_regex, ignorecase=true)

- name: Move {{ cluster_node }} out of maintenance mode.
  block:
    - name: "Clear maintenance attributes for {{ cluster_node }}."
      ansible.builtin.command: "crm_attribute --node {{ cluster_node }} --name maintenance --delete"
      changed_when: true

    - name: "Wait for {{ cluster_node }} changes to stabilize."
      ansible.builtin.command: "crm_resource --wait"
      changed_when: false
      ignore_errors: true
      timeout: "{{ beegfs_ha_common_pacemaker_wait_timeout }}"
  become: true
  delegate_to: "{{ cluster_automation_node }}"
  when: maintenance_query["stdout"] | regex_search(beegfs_ha_common_pacemaker_true_regex, ignorecase=true)
