# meta_26 - BeeGFS HA Metadata Resource Group

# This is a template for BeeGFS HA metadata resource group. Review all comments and update with all expected values.
# IMPORTANT: All capitalized words in angled brackets must be updated.

# Type of BeeGFS service the HA resource group will manage. Choices: management, metadata, storage.
beegfs_service: metadata


beegfs_ha_beegfs_meta_conf_resource_group_options:
  # BeeGFS HA resource service port. 8005 is the default BeeGFS metadata service port number; Each BeeGFS HA metadata
  # service resource must have a unique port number.
  connMetaPortTCP: 8265
  connMetaPortUDP: 8265

  # NUMA node binding for BeeGFS service. This should be defined at the resource group level. This NUMA policy will be
  # applied whenever and wherever the BeeGFS service resides. This can provide significant performance increases by
  # avoiding the cache misses between NUMA nodes.
  tuneBindToNumaZone: 0


# List of metadata floating IP definitions in the form host_interface:ip_address/cidr_subnet_mask.
# This information is used to communicate with the BeeGFS management resource. Therefore, these definitions must
# be on the same subnet as beegfs_ha_mgmtd_floating_ip value in group_vars/ha_cluster.yml. Any unusable definitions
# will be ignored which is specially useful when the definitions differ based on the host.
floating_ips:
  # - <IFACE>:<IP_ADDRESS>/<CIDR_MASK>
  - i2b:100.1.12.26/16
  - i1b:100.1.11.26/16


beegfs_targets:
  # E-Series storage target. Change this to any desired E-Series storage.
  netapp_07:
    eseries_storage_pool_configuration:
      - name: beegfs_m25_m26_m29_m30
        # Storage pool/volume group RAID type. Choices: raid0, raid1, raid5, raid6, raidDiskPool
        # RAID 1 mirrors the data between two drives which is the recommended storage type for management and metadata
        # services. If this storage pool is shared with other services this value must be the same on all definitions.
        raid_level: raid1

        # Total drive count for the storage pool. RAID 1 requires even number of drives. If this storage pool is shared
        # with other services this value must be the same on all definitions.
        criteria_drive_count: 4

        secure_pool: false
        common_volume_configuration:
          segment_size_kb: 128

        # BeeGFS metadata service requires only one volume.
        volumes:
          # Size of the BeeGFS metadata service volume in percentage of total storage pool capacity.
          # This percentage is shown as an example.  Depending on your configuration, adjust the percentage to account 
          # for overprovisioning.
          - owning_controller: B
            size: 23.75
            read_cache_enable: true
            read_ahead_enable: false
