- name: Ensure the required HA packages are installed (RedHat/CentOS - Management/Metadata/Storage).
  yum:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    allow_downgrade: true
    name:
      - "corosync-{{ beegfs_ha_corosync_version }}*"
      - "pacemaker-{{ beegfs_ha_pacemaker_version }}*"
      - "fence-agents-all{% if beegfs_ha_fence_agents_all_version is defined%}-{{beegfs_ha_fence_agents_all_version}}*{% endif %}"
      - "pcs-{{ beegfs_ha_pcs_version }}*"
  when: '"management" in node_info["services"] or "metadata" in node_info["services"] or "storage" in node_info["services"]'
  become: true

- name: Ensure pcsd daemon is running and enabled.
  systemd:
    name: pcsd
    state: started
    enabled: true
  become: true

- name: Ensure mailx is installed for alerts (RedHat/CentOS).
  yum:
    state: present
    name: mailx
  when: beegfs_ha_enable_alerts == True
  become: true

- name: Ensure NTP is installed (RedHat/CentOS).
  yum:
    state: latest
    name: ntp
  when: beegfs_ha_ntp_enabled == True
  become: true

- name: Ensure Chrony is uninstalled (RedHat/CentOS).
  yum:
    state: absent
    name: chrony
  when: beegfs_ha_ntp_enabled == True
  become: true
