- name: Add BeeGFS YUM repository (RedHat/CentOS - Client).
  yum_repository:
    name: beegfs
    description: BeeGFS YUM Repo
    file: beegfs_rhel7
    baseurl: "{{ beegfs_ha_rhel_repository_base_url }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ beegfs_ha_rhel_repository_gpgkey }}"
  become: true

- name: Ensure NTP is installed (RedHat/CentOS).
  block:
    - name: Ensure NTP is installed (RedHat/CentOS).
      ansible.builtin.yum:
        state: latest
        name: ntp
      become: true
    - name: Ensure Chrony is uninstalled (RedHat/CentOS - Client).
      ansible.builtin.yum:
        state: absent
        name: chrony
      become: true
  when: beegfs_ha_ntp_enabled == True

- name: Ensure Chrony is installed (RedHat/CentOS - Client).
  block:
    - name: Ensure Chrony is installed (RedHat/CentOS - Client).
      ansible.builtin.yum:
        state: latest
        name: chrony
      become: true
    - name: Ensure NTP is uninstalled (RedHat/CentOS - Client).
      ansible.builtin.yum:
        state: absent
        name: ntp
      become: true
  when: beegfs_ha_chrony_enabled == True

- name: Get kernel version (RedHat/CentOS - Client).
  ansible.builtin.command: "uname -r"
  register: kernel_version
  failed_when: "kernel_version['rc'] != 0"
  changed_when: False
  become: true

- name: Ensure kernel-devel is installed (RedHat/CentOS - Client).
  ansible.builtin.yum:
    state: present
    name: "kernel-devel-{{ kernel_version['stdout'] }}"
  become: true

- name: Ensure the BeeGFS client package is installed (RedHat/CentOS - Client).
  ansible.builtin.yum:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    allow_downgrade: true
    name:
      - "beegfs-client{% if beegfs_ha_beegfs_version is defined and beegfs_ha_beegfs_version %}-{{ beegfs_ha_beegfs_version }}*{% endif %}"
      - "beegfs-helperd{% if beegfs_ha_beegfs_version is defined and beegfs_ha_beegfs_version %}-{{ beegfs_ha_beegfs_version }}*{% endif %}"
      - "beegfs-utils{% if beegfs_ha_beegfs_version is defined and beegfs_ha_beegfs_version %}-{{ beegfs_ha_beegfs_version }}*{% endif %}"
  become: true
