- name: Ensure the required HA packages are installed (RedHat/CentOS - Remote Node).
  yum:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    allow_downgrade: true
    name:
      - "pacemaker-remote-{{ beegfs_ha_pacemaker_remote_version }}*"
  when: '"management" in node_info["services"] or "metadata" in node_info["services"] or "storage" in node_info["services"]'
  become: true

- name: Ensure pcsd daemon is running and enabled (RedHat/CentOS - Remote Node).
  systemd:
    name: pacemaker_remote
    state: started
    enabled: true
  become: true

- name: Ensure mailx is installed for alerts (RedHat/CentOS - Remote Node).
  yum:
    state: present
    name: mailx
  when: beegfs_ha_enable_alerts == True
  become: true

- name: Ensure NTP is installed (RedHat/CentOS - Remote Node).
  block:
    - name: Ensure NTP is installed (RedHat/CentOS - Remote Node).
      yum:
        state: latest
        name: ntp
      become: true
    - name: Ensure Chrony is uninstalled (RedHat/CentOS - Remote Node).
      yum:
        state: absent
        name: chrony
      become: true
  when: beegfs_ha_ntp_enabled == True

- name: Ensure Chrony is installed (RedHat/CentOS - Remote Node).
  block:
    - name: Ensure Chrony is installed (RedHat/CentOS - Remote Node).
      yum:
        state: latest
        name: chrony
      become: true
    - name: Ensure NTP is uninstalled (RedHat/CentOS - Remote Node).
      yum:
        state: absent
        name: ntp
      become: true
  when: beegfs_ha_chrony_enabled == True