- name: Add BeeGFS ZYPPER repository (SUSE).
  zypper_repository:
    state: present
    name: beegfs
    description: BeeGFS ZYPPER Repo
    repo: "{{ beegfs_ha_suse_repository_base_url }}"
    autorefresh: true
    auto_import_keys: true
  when: "'.repo' in beegfs_ha_suse_repository_base_url"
  become: true

- name: Create BeeGFS repo file (SUSE).
  template:
    src: "{{ lookup('netapp_eseries.beegfs.eseries_template_path', 'common/suse_repo.j2') }}"
    dest: "/etc/zypp/repos.d/beegfs.repo"
  when: "'.repo' not in beegfs_ha_suse_repository_base_url"
  become: true

- name: Ensure the BeeGFS management package is installed (SUSE - Management).
  zypper:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    name: "beegfs-mgmtd={{ beegfs_ha_beegfs_version }}*"
  register: beegfs_mgmtd_package
  when: '"management" in node_info["services"]'
  become: true

- name: Stop beegfs-mgmtd service.
  systemd:
    name: beegfs-mgmtd.service
    state: stopped
    enabled: false
  when: beegfs_mgmtd_package['changed'] == True
  become: true

- name: Ensure the BeeGFS metadata package is installed (SUSE - Metadata).
  zypper:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    name: "beegfs-meta={{ beegfs_ha_beegfs_version }}*"
  register: beegfs_meta_package
  when: '"metadata" in node_info["services"]'
  become: true

- name: Stop beegfs-metadata service.
  systemd:
    name: beegfs-meta.service
    state: stopped
    enabled: false
  when: beegfs_meta_package['changed'] == True
  become: true

- name: Ensure the BeeGFS storage package is installed (SUSE - Storage).
  zypper:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    name: "beegfs-storage={{ beegfs_ha_beegfs_version }}*"
  register: beegfs_storage_package
  when: '"storage" in node_info["services"]'
  become: true

- name: Stop beegfs-storage service.
  systemd:
    name: beegfs-storage.service
    state: stopped
    enabled: false
  when: beegfs_storage_package['changed'] == True
  become: true

- name: Ensure the BeeGFS infiniband package is installed (SUSE - Metadata/Storage).
  zypper:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    name: libbeegfs-ib
  when: '("metadata" in node_info["services"] or "storage" in node_info["services"]) and beegfs_ha_enable_rdma'
  become: true
