- name: Add BeeGFS ZYPPER repository (SUSE - Client).
  zypper_repository:
    state: present
    name: beegfs
    description: BeeGFS ZYPPER Repo
    repo: "{{ beegfs_ha_suse_repository_base_url }}"
    autorefresh: true
    auto_import_keys: true
  when: "'.repo' in beegfs_ha_suse_repository_base_url"
  become: true

- name: Create BeeGFS repo file (SUSE - Client).
  ansible.builtin.template:
    src: "{{ lookup('netapp_eseries.beegfs.eseries_template_path', 'common/suse_repo.j2') }}"
    dest: "/etc/zypp/repos.d/beegfs.repo"
  when: "'.repo' not in beegfs_ha_suse_repository_base_url"
  become: true

- name: Ensure NTP is installed (SUSE - Client).
  block:
    - name: Ensure NTP is installed (SUSE - Client).
      zypper:
        state: latest
        name: ntp
      become: true
    - name: Ensure Chrony is uninstalled (SUSE - Client).
      zypper:
        state: absent
        name: chrony
      become: true
  when: beegfs_ha_ntp_enabled == True

- name: Ensure Chrony is installed (SUSE - Client).
  block:
    - name: Ensure Chrony is installed (SUSE - Client).
      zypper:
        state: latest
        name: chrony
      become: true
    - name: Ensure NTP is uninstalled (SUSE - Client).
      zypper:
        state: absent
        name: ntp
      become: true
  when: beegfs_ha_chrony_enabled == True

- name: Enable unsupported modules (SUSE - Client).
  replace:
    path: /etc/modprobe.d/10-unsupported-modules.conf
    regexp: 'allow_unsupported_modules 0'
    replace: 'allow_unsupported_modules 1'
  when: beegfs_ha_suse_allow_unsupported_module == True
  become: true

- name: Get kernel version (SUSE - Client).
  shell: "uname -r | cut -f 1,2 -d \"-\""
  register: uname_shell_output
  failed_when: "uname_shell_output['rc'] != 0"
  changed_when: false
  become: true

- name: Ensure kernel-devel is installed (SUSE - Client).
  zypper:
    name: "kernel-devel={{ uname_shell_output['stdout_lines'][0] }}"
    state: present
  become: true

- name: Ensure kernel-default-devel is installed (SUSE - Client).
  zypper:
    name: "kernel-default-devel={{ uname_shell_output['stdout_lines'][0] }}"
    state: present
  become: true

- name: Ensure kernel-source is installed (SUSE - Client).
  zypper:
    name: "kernel-source={{ uname_shell_output['stdout_lines'][0] }}"
    state: present
  become: true

- name: Ensure the BeeGFS client package is installed (SUSE - Client).
  zypper:
    state: "{% if beegfs_ha_force_beegfs_patch_upgrade %}latest{% else %}present{% endif %}"
    name:
      - "beegfs-client"
      - "beegfs-helperd"
      - "beegfs-utils"
  become: true
