- name: Ensure BeeGFS client package is uninstalled (Debian/Ubuntu - Client).
  apt:
    state: absent
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
  when: inventory_hostname in groups[beegfs_ha_ansible_client_group]
  become: true
