- name: Ensure the BeeGFS management package is installed (RedHat/CentOS - Management).
  yum:
    state: absent
    name: beegfs-mgmtd
  when: '"management" in node_info["services"]'
  become: true

- name: Ensure the BeeGFS metadata package is installed (RedHat/CentOS - Metadata).
  yum:
    state: absent
    name: beegfs-meta
  when: '"metadata" in node_info["services"]'
  become: true

- name: Ensure the BeeGFS storage package is installed (RedHat/CentOS - Storage).
  yum:
    state: absent
    name: beegfs-storage
  when: '"storage" in node_info["services"]'
  become: true

- name: Ensure the BeeGFS infiniband package is installed (RedHat/CentOS - Metadata/Storage).
  yum:
    state: absent
    name: libbeegfs-ib
  when: '("metadata" in node_info["services"] or "storage" in node_info["services"]) and beegfs_ha_enable_rdma'
  become: true

- name: Ensure the required HA packages are installed (RedHat/CentOS - Management/Metadata/Storage).
  yum:
    state: absent
    name:
      - corosync
      - pacemaker
      - pcs
      - fence-agents-all
  when: '"management" in node_info["services"] or "metadata" in node_info["services"] or "storage" in node_info["services"]'
  become: true

- name: Ensure the BeeGFS client package is installed (RedHat/CentOS - Client).
  yum:
    state: absent
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
  when: inventory_hostname in groups[beegfs_ha_ansible_client_group]
  become: true
