- name: Ensure the BeeGFS client package is installed (SUSE - Client).
  zypper:
    state: absent
    name:
      - "beegfs-client={{ beegfs_ha_beegfs_version }}"
      - "beegfs-helperd={{ beegfs_ha_beegfs_version }}"
      - "beegfs-utils={{ beegfs_ha_beegfs_version }}"
  when: inventory_hostname in groups[beegfs_ha_ansible_client_group]
  become: true
